### ISSUE TITLE
ADD more datasources: Europe

### ISSUE THREAD

**Issue by allanlaal** [patrik-martinko/app-cost-of#1]
currently the fuel prices are only for Slovakia

we should use fuelo.net or similar to get fuel prices for more countries

**Comment by allanlaal** [comment]
initially the price could be polled for the country specified in plugin options, lets go more complex later, maybe..

**Comment by allanlaal** [comment]
DEPRECATED:

fuelo.net API does not currently return prices per country nor area (only an EU? average)

I sent them this letter:

	  Feature Request: API: location specific price
	  
	  please add more location parameters to the http://fuelo.net/api/price API request:
	  
	  a) returns the average prices for fuels in that country
	  extra GET parameter: `country` (lowercase ISO 3166-1 alpha-2 country code, i.e: bg, de, fi, ee, dk, gb)
	  
	  b) returns the average around a GPS coordinate:
	  extra GET parameters: `lat`, `lon`, `distance` (like in http://fuelo.net/api/near )
	  
	  optional: 
	  `limit` 
	  if `limit`  is set, then returns the average of the first x results. `limit` =1 can give a risky, but fast answer, whilst `limit` =1000 would give a very accurate average. depends on what its used for
	  
	  c) get an average fuel price for brand id
	  extra GET parameter:  `brand_id`
	  
	  I think `limit` would be a bonus here too
	  
	  d) get fuel price for specific Gas Station
	  extra GET parameter:  `gasstation_id` (the same as the `id` field in the answer of https://fuelo.net/api/gasstation )
	  

will keep this ticket posted on any news

**Comment by patrik-martinko** [comment]
Yes, I planned to add more countries based on demand and available APIs. Slovakia was only "beta" because I knew our statistics API and because of my free time. I also didn't know if this functionality will be useful & attractive for other people. 🙂

Thanks for the tip about API. I'll check the fuelo.net API and add more countries if this API will be usable.

**Comment by allanlaal** [comment]
@patrik-martinko Fuelo said their API is deprecated and without my changes its unusable in its current state - I tested it exhaustively. You can get the average fuel price for Bulgaria though, so yeah :D

**Comment by allanlaal** [comment]
maybe there's an EU open API somewhere? a shallow google did not yield any results, but it sounds like sth 💗EU💗 would have

**Comment by patrik-martinko** [comment]
EU has some data but in form of XLSX or PDF files 🙂 https://ec.europa.eu/energy/data-analysis/weekly-oil-bulletin_en
(At least I've found only this form of data source from the EU)

An XLSX file is parsable, but it's time-consuming to develop a script to parse not-so-consistent data 🙂

I've also found HERE Prices API but I haven't checked it so far. https://developer.here.com/documentation/fuel-prices/dev_guide/topics/api-reference.html

**Comment by patrik-martinko** [comment]
Good news 🙂

I've made a parser for the EU data files so the EU countries are included in the app. I've also made the website [costof.app](https://costof.app) where you can set the values and find out the current prices.

The version 2.0.0 has been approved in the Chrome Web Store.

Enjoy 🙂
