### ISSUE TITLE
FIX distance should be converted using current Locale

### ISSUE THREAD

**Issue by allanlaal** [patrik-martinko/app-cost-of#2]
my locale has `,` as a thousands separator :vomiting_face:, so the plugin thinks a 2600km roadtrip is 2.6 km :D

**Comment by patrik-martinko** [comment]
Thanks for reporting 👍 

I'm going to fix this.

**Comment by patrik-martinko** [comment]
I forgot to reply. This issue was fixed and already approved in web stores (v1.0.3).
