### ISSUE TITLE
Extension seems to break if your destination is over 1000 km away

### ISSUE THREAD

**Issue by CookiesByte** [patrik-martinko/app-cost-of#3]
May be related to this issue: https://github.com/patrik-martinko/app-cost-of/issues/2

![chrome_xfuRmgDdqx](https://user-images.githubusercontent.com/58192116/178992613-bf2a50bd-6f9b-4f2b-81ae-8ef7ee14ad1f.png)

Edit: In German we separate thousands with `.`

**Comment by patrik-martinko** [comment]
Thank you for reporting. I'll check it.

**Comment by patrik-martinko** [comment]
> German we separate thousands with .

That was the problem. I didn't expect that some country uses dot as the thousand separator.

I fixed it and submitted the update `v2.0.4` to the webstore, but it usually takes some time while they approve an update.

**Comment by patrik-martinko** [comment]
The version `v2.0.4` has been approved.
